spring.application.name=jwt_pract
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=qwertyuioplkjhgfdsazxcvbnasdfghjmcrtyhn
jwt.expiration=3600000